name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Adjust if you use a different JDK version
        distribution: 'adopt'

    - name: Build and Run Tests
      run: |
        javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Form.java GenealogyRequestReview.java WorkflowTable.java
        javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar GenealogyRequestReviewTest.java
        java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore GenealogyRequestReviewTest
